import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
<<<<<<< HEAD
<<<<<<< HEAD
  title: 'PENSANDO EL VOLEY',
=======
  title: 'LEYENDO EL VOLEY',
>>>>>>> c1ca779 (que no se repita la consinga dos veces)
=======
  title: 'PENSANDO EL VOLEY',
>>>>>>> d6a7b4f (el titulo de la app que sea pensando el voley)
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

